spring:
  application:
    name: facture-service
  datasource:
    url: jdbc:postgresql://postgres:5432/facture
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Global parameter
globalParam: 100

# Additional parameter
monParam: 200

# Email parameter
email: "admin@venteplus.com"

# Service specific configuration
facture:
  service:
    description: "Invoice Management Service"
    version: "1.0.0"
