spring:
  application:
    name: produit-service
  datasource:
    url: jdbc:postgresql://postgres:5432/produit
    username: postgres
    password: 1023
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

# Service specific configuration
produit:
  service:
    description: "Product Management Service"
    version: "1.0.0"

# Cloudinary configuration for image storage
cloudinary:
  cloud_name: dwpglwihw
  api_key: 382737757656489
  api_secret: EohXmvnC9k8Rp8Edikkao0g1pJg

# Global parameter
globalParam: 100

# Additional parameter
monParam: 200

# Email parameter
email: "admin@venteplus.com"
